rule all:
    input:
        p1 = expand('{out_dir}/{{data}}_1.trimed.fastq.gz'.format(out_dir=config['out_dir']), data=config['SRR_id']),
        p2 = expand('{out_dir}/{{data}}_2.trimed.fastq.gz'.format(out_dir=config['out_dir']), data=config['SRR_id']),

rule fetch:
    params:
        srr = lambda wildcards: config['SRR_id'][wildcards.data],
        dir = config['out_dir']
    log:
        'logs/{data}.log'
    output:
        '{out_dir}/{data}_1.fastq.gz',
        '{out_dir}/{data}_2.fastq.gz'
    shell:
        # 'fastq-dump -O {params.dir} --gzip {params.srr} 2> {log}'
        'bash download_srr.sh {params.srr} {params.dir} {log[0]}'

rule trim:
    params:
        trim_cmd = config['trim_cmd'],
        trim_param = config['trim_param']
    input:
        '{out_dir}/{data}_1.fastq.gz',
        '{out_dir}/{data}_2.fastq.gz'
    output:
        '{out_dir}/{data}_1.trimed.fastq.gz',
        '{out_dir}/{data}_2.trimed.fastq.gz'
    shell:
        'bash do_trim.sh "{params.trim_cmd}" {input} {output} "{params.trim_param}"'
