experiments:
  mytest:
    bam: '/project2/xinhe/yifan/Footprint/test/CN_18.bam'
    bed: '/project2/xinhe/yifan/Footprint/test/CN_uniq_peaks.bed'
    read_method: 'cat'  # how to view BED file (usually cat OR zcat)
motifs:  # one motif database per config flie (the ones other than the first will be ignored)
  recalMotifs: '../recalibratedMotifs/'
genome_assembly: # only one genome assembly as well
  hg38:
    fasta: '/project2/xinhe/yifan/refGenome/hg38.fa'
    size: '/project2/xinhe/yanyul/databases/hg38/hg38.chrom.sizes'
active_motifs:
  fimo_threshold: 1e-4
  output_threshold: 1 # 6e-7
centipede:
  script: '/scratch/midway2/xinhe/repo/which_gen_vars/src/fitCentipedeV2.R'
  window_size: 200
alignment_params:
  ncpus: 1
  cmd: 'bowtie \{ref\} -p \{threads\} -m 1 -X 2000 --chunkmbs 2000 -1 \{fastq1\} -2 \{fastq2\} --sam \{sam\}'
  # cmd: for your reference \{fastq1\} \{fastq2\} \{sam\} \{ref\} \{threads\}
  clean_cmd: 'java -jar /project2/xinhe/yanyul/softwares/picard.jar \
  MarkDuplicates \
  I=\{input\} \
  O=\{output\} \
  M=\{output\}.metric.txt \
  REMOVE_DUPLICATES=true'
  # clean_cmf: \{input\} \{output\}
test_motifs: 'M00001,M00008'  # only for debugging
debug: True
sort_bam: True
