experiments:
  E081:
    fastq: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203400.fastq.gz'
    bed: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E081-DNase.macs2.narrowPeak.sorted'  # ATTENTION: only take compressed bed file
    read_method: 'cat'
#  NSC_27:
#     fastq: 'something'
#    bed: 'something'
#  NSC_41d_1:
#    fastq: 'something'
#    bed: 'something'
#  NSC_41d_2:
#    fastq: 'something'
#    bed: 'something'
# variants:
#   yuwen: 'something'
motifs:
  recalMotifs: '../recalibratedMotifs/'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19/hg19.fa'
  size: '/project2/xinhe/yanyul/databases/hg19/hg19.chrom.sizes'
active_motifs:
  extend_bed: 50  # extend input region a little bit to consider some edge cases
                  # where footprint peak is incompletely called
  score_threshold: 10000  # log likelihood ratio (flat background base distribution)
  occurence_threshold: 10000
centipede:
  script: ''
  window_size: 100
ncpus: 1
