experiments:
  E081:
    fastq: 'something'
    bed: 'something'  # ATTENTION: only take compressed bed file
  NSC_27d:
    fastq: 'something'
    bed: 'something'
  NSC_41d_1:
    fastq: 'something'
    bed: 'something'
  NSC_41d_2:
    fastq: 'something'
    bed: 'something'
variants:
  yuwen: 'something'
motifs:
  recalMotifs: 'something'
genome_assembly:
  fasta: 'something'
  size: 'something'
active_motifs:
  extend_bed: 50  # extend input region a little bit to consider some edge cases
                  # where footprint peak is incompletely called
  score_threshold: 10000  # log likelihood ratio (flat background base distribution)
  occurence_threshold: 10000
centipede:
  script: 'path of centipede script'
  window_size: 100
